version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/codecov/codecov
  codecov: codecov/codecov@3.1.1

executors:
  base-docker-executor:
    docker:
      - image: circleci/ruby:2.7.1

jobs:
  upload-to-codecov:
    executor: base-docker-executor
    steps:
      - checkout
      - codecov/upload

workflows:
  test_suite:
    jobs:
      - upload-to-codecov
