version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/codecov/codecov
  codecov: codecov/codecov@3.1.1

executors:
  base-docker-executor:
    docker:
      - image: circleci/ruby:2.7.1

commands:
  install_dependencies:
    steps:
      - run:
          name: Install Ruby Dependencies
          command: bundle install --deployment

jobs:
  rspec:
    executor: base-docker-executor
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Setup Database
          command: bundle exec rake db:setup
      - run:
          name: Run Rspec
          command: rspec

  upload-to-codecov:
    executor: base-docker-executor
    steps:
      - checkout
      - codecov/upload

workflows:
  test_suite:
    jobs:
      - rspec
      - upload-to-codecov:
          requires:
            - rspec
